# 开发环境 application-dev.yml
auto-table:
  # 开启自动建表
  enable: true
  record-sql:
    # 开启SQL记录
    enable: true
    # 当前版本（此处可保持与计划上线的版本号一致，方便管理SQL文件）
    version: 1.0.0
    # 记录到数据库（如果是多数据源，则会根据不同数据源，记录到不同的库）
    record-type: db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/automated_java_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: mysql_PjAFkh